CONTRABAND_ITEMS:
- 338
- 40
- 39
SINGLE_EFFECTS:
  BLINDNESS: 'YES'
  CONFUSION: 'YES'
  SLOW: 'YES'
  FAST_DIGGING: 'NO'
  SLOW_DIGGING: 'YES'
  JUMP: 'NO'
COMBINED_EFFECTS:
  '6':
  - BLINDNESS
  - CONFUSION
  - SLOW
